### ISSUE TITLE
Support for letsencrypt

### ISSUE THREAD

**Issue by runningman84** [zuazo/ssl_certificate-cookbook#20]
I am thinking about how to integrate letsencrypt.org support?

**Comment by zuazo** [comment]
OK. I'm going to try to get a certificate from [Let's Encrypt](https://letsencrypt.org/). Do you know if they have any special requirements?

**Comment by runningman84** [comment]
Let's Encrypt needs a working webserver where can serve some kind of auth code to the ca. The full docs are here:
https://github.com/letsencrypt/letsencrypt
It could be tricky to implement this because the ssl_certificate cookbook would not work without some kind of webserver.

**Comment by runningman84** [comment]
There seems to be a problem

Ok I have build a cookbook which does the letscrypt installation using the bash script and which requests the certificate.

My idea is to start with a self signed certificate and replace it with a letsencrypt certificate once the process is done. My recipe looks like this:

```
cert = ssl_certificate 'my-letsencrypt' do
  if File.exists?("/etc/letsencrypt/certs/#{domain}/cert.pem")
    key_path "/etc/letsencrypt/certs/#{domain}/privkey.pem"
    cert_path "/etc/letsencrypt/certs/#{domain}/cert.pem"
    chain_path "/etc/letsencrypt/certs/#{domain}/fullchain.pem"
  else
    namespace node['my-letsencrypt']['ssl']
  end
  notifies :restart, 'service[nginx]'
end
```

This results in this configuration:
```

  ssl on;
  ssl_certificate /etc/ssl/certs/my-letsencrypt.pem.chained.pem;
  ssl_certificate_key /etc/letsencrypt/certs/ssltest.aws.mytest.de/privkey.pem;

  ssl_prefer_server_ciphers on;

  # Enable this if your want HSTS (recommended)
  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";

  ssl_stapling on;
  ssl_stapling_verify on;
  resolver 8.8.8.8;
```
As you can see the ssl_certificate cookbook mixes the stuff :/ it uses the certificate from the self signed ca and uses the private key from letsencrypt.

**Comment by zuazo** [comment]
Hi @runningman84 , thanks for all your work and explanations :wink: I will try to look at this in detail next week. I will need time because this is something completely new to me.

Regarding your last example, are you sure that those files exist before the chef run? I mean, if you are creating them with chef, the `File.exists?` will return false there because it runs at compile time.

**Comment by runningman84** [comment]
Hi zuazo have you had any time to do your own tests?

**Comment by zuazo** [comment]
@runningman84 No, I have not had time for this, sorry :disappointed: Anyway, at a quick glance, I think maybe this falls out of the scope of this cookbook, don't you think? It seems more appropriate for a wrapper cookbook considering the requirements.

Either way, I still have the intention to look in detail before taking a final decision. Feel free to discuss it here, preparing your examples, PRs or similar if you're in a hurry.

**Comment by zuazo** [comment]
I'm closing this. As I said, I think it falls outside the scope of this cookbook.

You can use the [`acme`](https://supermarket.chef.io/cookbooks/acme) cookbook to manage Let's Encrypt certificates with Chef.

Please, add a comment below if you want to continue the discussion and I will reopen the issue.
