### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jonathanmorley** [zuazo/ssl_certificate-cookbook#27]
I am looking to make use of the data bag fallback attribute, are there plans to make a new release soon?

**Comment by zuazo** [comment]
Hi @jonathanmorley,

Can you wait until this Sunday? I want to review the pending PRs before releasing it.

**Comment by jonathanmorley** [comment]
sure

**Comment by zuazo** [comment]
Version [`1.12.0`](https://github.com/zuazo/ssl_certificate-cookbook/releases/tag/1.12.0) released.
