### ISSUE TITLE
Make resolver changeable in the nginx template

### ISSUE THREAD

**Issue by runningman84** [zuazo/ssl_certificate-cookbook#29]
Right now the resolver is configured as 8.8.8.8 it would be cool if this value could be changed...

Using the current configured dns instead of 8.8.8.8 seems to be a better default?

**Comment by zuazo** [comment]
I guess you mean in the [nginx template](https://github.com/zuazo/ssl_certificate-cookbook/blob/1.12.0/templates/default/nginx.erb#L32) with OCSP stapling enabled, right?

**Comment by runningman84** [comment]
yes, in a Amazon VPC you might want to resolve to local dns servers in order to query local Route53 Zones...

**Comment by zuazo** [comment]
Implemented in master: 835072b2a812caaade9abf2dc3d2aa6e59e84314

**Comment by zuazo** [comment]
Released in [`2.0.0`](https://github.com/zuazo/ssl_certificate-cookbook/releases/tag/2.0.0)
